spring.application.name=HealthLogWebApp

spring.datasource.url=jdbc:mysql://localhost:3306/healthlog?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mailtrap (bi chan boi mang cong ty - tam thoi khong dung)
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=24937de4d37ae6
#spring.mail.password=d108cb73238bdf
#spring.mail.default-encoding=UTF-8
spring.mail.host=localhost
spring.mail.port=1025

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=no-reply@healthlog.local
app.frontend-url=http://localhost:8080