package com.healthlog.app.service.feedbackservice.model;

public enum FeedbackType {

	WEIGHT_NO_RECORD,
	WEIGHT_BIG_CHANGE,
	WEIGHT_SUDDEN_CHANGE,
	WEIGHT_GOAL_ACHIEVED,

	SLEEP_NO_RECORD,
	SLEEP_NO_GOAL,
	SLEEP_SHORT,
	SLEEP_GOOD,
	SLEEP_CONTINUOUS_SHORT,

	WATER_NO_RECORD,
	WATER_NO_GOAL,
	WATER_LOW,
	WATER_ALMOST,
	WATER_COMPLETE,
	WATER_EXCESS,

	STEP_NO_RECORD,
	STEP_NO_GOAL,
	STEP_LOW,
	STEP_ALMOST,
	STEP_COMPLETE,

	DAILY_COMPLETE,
	CONTINUOUS_RECORD
}